export enum LC_Type1 {
  EvergreenNeedleleaf = 1,
  EvergreenBroadleaf = 2,
  DeciduousNeedleleaf = 3,
  DeciduousBroadleaf = 4,
  MixedForest = 5,
  ClosedShrublands = 6,
  OpenShrublands = 7,
  WoodySavannas = 8,
  Savannas = 9,
  Grasslands = 10,
  Wetlands = 11,
  Croplands = 12,
  Urban = 13,
  CroplandMosaic = 15,
  Snow = 16,
  Barren = 17,
}
